spring:
  application:
    name: pokedex-api
  datasource:
    url: jdbc:h2:mem:pokedex-api;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:static/data.sql
